### PR TITLE
Added phantomCassandraTimeout setting

### PR DESCRIPTION
**Pull request by tstone**
Added `phantomCassandraTimeout` setting to allow the start up timeout of cassandraunit to be configured

### CODE REVIEW

**Comment by alexflav23** [comment]
Hi @tstone,

Many thanks for your contribution. We have merged this repo into the main phantom repo as a sub project, so for future contributions could you please check them in there? This repository will be deprecated in the process sometime next week after we automate the final few issues in the main repo.

Regards.

**Comment by alexflav23** [comment]
Hi @tstone,

Just wanted to assure you I have merged this internally. This repo is going away, but you can still check in to the main phantom project, where phantom-sbt is now located as a sub-project.

Regards.

**Comment by tstone** [comment]
Thanks.

**Comment by tstone** [comment]
By "main phantom project" were you referring to here:

https://github.com/outworkers/phantom/blob/develop/phantom-sbt/src/main/scala/com/websudos/phantom/sbt/SbtPlugin.scala

**Pull request closed without merging**
